
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sqlite3
from datetime import date
import os
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label
from PIL import Image,ImageTk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("C:/Users/Kushal/OneDrive/Desktop/ShopLens/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def mainScreen(canvas):


    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        1440.0,
        71.0,
        fill="#0F3ADA",
        outline="")

    canvas.create_text(
        10.0,
        95.0,
        anchor="nw",
        text="Enter Customer Name  ",
        fill="#000000",
        font=("Inter Bold", 21 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        187.5,
        139.5,
        image=entry_image_1
    )
    customerBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial',16)
    )
    customerBox.place(
        x=10.0,
        y=125.0,
        width=355.0,
        height=27.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        615.5,
        139.5,
        image=entry_image_2
    )
    emailBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16)
    )
    emailBox.place(
        x=438.0,
        y=125.0,
        width=355.0,
        height=27.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        187.5,
        215.5,
        image=entry_image_3
    )
    productBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16)
    )
    productBox.place(
        x=10.0,
        y=201.0,
        width=355.0,
        height=27.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        615.5,
        215.5,
        image=entry_image_4
    )
    quantityBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16)
    )
    quantityBox.place(
        x=438.0,
        y=201.0,
        width=355.0,
        height=27.0
    )

    canvas.create_text(
        438.0,
        95.0,
        anchor="nw",
        text="Enter Customer Email",
        fill="#000000",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_text(
        10.0,
        169.0,
        anchor="nw",
        text="Enter Product Name",
        fill="#000000",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_text(
        438.0,
        169.0,
        anchor="nw",
        text="Enter Quantity",
        fill="#000000",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_rectangle(
        1030.0,
        696.0,
        1385.0,
        746.0,
        fill="#0F3ADA",
        outline="")

    canvas.create_text(
        1036.0,
        708.2451171875,
        anchor="nw",
        text="Total Amount:",
        fill="#FFFFFF",
        font=("Inter", 25 * -1,"bold")
    )

    canvas.create_rectangle(
        0.0,
        262.0,
        1440.0,
        314.0,
        fill="#0F3ADA",
        outline="")

    canvas.create_text(
        10.0,
        275.0,
        anchor="nw",
        text="Sr.No",
        fill="#FFFFFF",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_text(
        582.0,
        275.0,
        anchor="nw",
        text="Quantity",
        fill="#FFFFFF",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_text(
        866.0,
        275.0,
        anchor="nw",
        text="Price Per Unit",
        fill="#FFFFFF",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_text(
        229.0,
        275.0,
        anchor="nw",
        text="Product Name",
        fill="#FFFFFF",
        font=("Inter Bold", 21 * -1)
    )

    canvas.create_text(
        1200.0,
        275.0,
        anchor="nw",
        text="Price",
        fill="#FFFFFF",
        font=("Inter Bold", 21 * -1)
    )

    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_5.png"))
    entry_bg_5 = canvas.create_image(
        720.0,
        489.0,
        image=entry_image_5
    )
    billArea = Text(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16),
        state="disabled"
    )
    billArea.place(
        x=0.0,
        y=314.0,
        width=1440.0,
        height=348.0
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        1296.0,
        166.0,
        image=image_image_1
    )
    canvas.image = image_image_1


    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas.create_image(
        1302.5,
        721.0,
        image=entry_image_6
    )
    totalAmount = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        state="readonly"
    )
    totalAmount.place(
        x=1220.0,
        y=696.0,
        width=165.0,
        height=50.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    registerButton = Button(
        text="Register & Update",
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat",
        bg="#0F3ADA",
        fg="#FFFFFF",
        font=("Inter", 20, "bold")
    )
    registerButton.place(
        x=24.0,
        y=10.0,
        width=246.0,
        height=50.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    mostSoldButton = Button(
        text="Most Sold Product",
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat",
        bg="#0F3ADA",
        fg="#FFFFFF",
        font=("Inter", 20, "bold")
    )
    mostSoldButton.place(
        x=316.0,
        y=10.0,
        width=266.0,
        height=50.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    generateBill = Button(
        text="Generate Bill",
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat",
        bg="#0F3ADA",
        fg="#FFFFFF",
        font=("Inter", 20, "bold")
    )
    generateBill.place(
        x=620.0,
        y=699.0,
        width=200.0,
        height=50.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    checkButton = Button(
        text="Check",
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat",
        bg="#0F3ADA",
        fg="#FFFFFF",
        font=("Inter", 16, "bold")
    )
    checkButton.place(
        x=836.0,
        y=120.0,
        width=89.25732421875,
        height=37.6552734375
    )
    # window.resizable(False, False)
    # window.mainloop()
    con = sqlite3.connect("ShopLens.db")
    cursor = con.cursor()
    query = ""

    customerName = customerBox.get().lower().strip()
    email = emailBox.get().lower().strip()
    productName = productBox.get().lower().strip()
    quantity = quantityBox.get()
    purDate = date.today()

if __name__ == "__main__":
    window = Tk()

    window.geometry("1440x788")
    window.configure(bg="#A5D1E1")

    canvas = Canvas(
        window,
        bg="#A5D1E1",
        height=788,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    mainScreen(canvas)
    window.resizable(False,False)
    window.mainloop()
