
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Kushal\OneDrive\Desktop\ShopLens\build\assets\mostSold")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def mostSoldGraph(canvas,shopname,switch_to_mainmenu):
    canvas.configure(bg="#A5D1E1")
    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        1440.0,
        71.0,
        fill="#0F3ADA",
        outline="")

    canvas.create_text(
        530.0,
        10.0,
        anchor="nw",
        text="Most Sold Product",
        fill="#FFFFFF",
        font=('Inter', 34,'bold')
    )

    canvas.create_rectangle(
        0.0,
        13.0,
        114.0,
        53.0,
        fill="#0F3ADA",
        outline="")

    homeButton = Button(text="Home", bg="#0F3ADA", fg="#FFFFFF", font=('Inter', 20, 'bold'), borderwidth=0,
                        highlightthickness=0,command=lambda :deleteforMainmenu())
    homeButton.place(x=0, y=13, width=114, height=40)

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        1404.0,
        35.0,
        image=image_image_1
    )
    canvas.image = image_image_1
    var = [homeButton]
    def deleteforMainmenu():
        for i in var:
            i.destroy()
        switch_to_mainmenu(shopname)
