
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sqlite3
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("C:/Users/Kushal/OneDrive/Desktop/ShopLens/build/assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def signinPage():
    # Creating database to store user data

    con = sqlite3.connect("ShopLens.db")
    cursor = con.cursor()
    query = "create table if not exists User(UserId integer primary key autoincrement, UserName varchar(255), Email varchar(255), Password varchar(255), ShopName varchar(255));"
    cursor.execute(query)

    # Creating UI

    window = Tk()

    window.geometry("1440x788")
    window.configure(bg = "#5D6794")


    canvas = Canvas(
        window,
        bg = "#5D6794",
        height = 788,
        width = 1440,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        720.0,
        0.0,
        1440.0,
        788.0,
        fill="#5B7699",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        720.0,
        338.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        370.0,
        46.0,
        1070.0,
        742.0,
        fill="#A5D1E1",
        outline="")

    canvas.create_text(
        498.0,
        520.0,
        anchor="nw",
        text="Enter Your Shop Name",
        fill="#000000",
        font=("Inter Bold", 29 * -1)
    )

    canvas.create_text(
        498.0,
        404.0,
        anchor="nw",
        text="Enter Your Username",
        fill="#000000",
        font=("Inter Bold", 29 * -1)
    )

    canvas.create_text(
        498.0,
        288.0,
        anchor="nw",
        text="Enter Your Password",
        fill="#000000",
        font=("Inter Bold", 29 * -1)
    )

    canvas.create_text(
        498.0,
        172.0,
        anchor="nw",
        text="Enter Your Email",
        fill="#000000",
        font=("Inter Bold", 29 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        720.5,
        226.5,
        image=entry_image_1
    )
    signEmailBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16)
    )
    signEmailBox.place(
        x=498.0,
        y=207.0,
        width=445.0,
        height=37.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        720.5,
        342.5,
        image=entry_image_2
    )
    signPassBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16),
        show="*"
    )
    signPassBox.place(
        x=498.0,
        y=323.0,
        width=445.0,
        height=37.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        720.5,
        458.5,
        image=entry_image_3
    )
    signUserBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16)
    )
    signUserBox.place(
        x=498.0,
        y=439.0,
        width=445.0,
        height=37.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        720.5,
        574.5,
        image=entry_image_4
    )
    shopnameBox = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=('Arial', 16)
    )
    shopnameBox.place(
        x=498.0,
        y=555.0,
        width=445.0,
        height=37.0
    )

    # Inserting values
    def insertUserDetails():
        # Fetching values from GUI

        email = str(signEmailBox.get().lower().strip())
        password = str(signPassBox.get().lower().strip())
        username = str(signUserBox.get().lower().strip())
        shopname = str(shopnameBox.get().lower().strip())
        query1 = "insert into User(UserName, Email, Password, ShopName) values(?,?,?,?)"
        values = [username, email, password, shopname]
        cursor.execute(query1, values)
        con.commit()
        canvas.create_text(
            573.0,
            603.0,
            anchor="nw",
            text="!!Registered User Successfully!!",
            fill="#000000",
            font=("Inter Bold", 20 * -1)
        )
        signEmailBox.delete(0, 'end')
        signPassBox.delete(0, 'end')
        signUserBox.delete(0, 'end')
        shopnameBox.delete(0, 'end')


    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    signButton = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda :insertUserDetails(),
        relief="flat"
    )

    signButton.place(
        x=599.0,
        y=636.0,
        width=261.0,
        height=75.0
    )

    canvas.create_text(
        637.0,
        62.0,
        anchor="nw",
        text="Sign In",
        fill="#000000",
        font=("Inter Bold", 50 * -1)
    )
    window.resizable(False, False)
    window.mainloop()

    con.close()








if __name__ == "__main__":
    signinPage()
